spring:
  application:
    name: todolist

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?
    user: postgres.omfdfdallvoeasibotqu&password=mHEUfrcTOtMKCxUr
    username: postgres.omfdfdallvoeasibotqu
    password: mHEUfrcTOtMKCxUr

server:
  port: 5555



