spring:
  application:
    name: GatewayAPI
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: AccountManagement
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: Weather
          uri: http://localhost:8891
          predicates:
            - Path=/weather/**
server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

debug: true